# Generated by Django 5.2.1 on 2025-05-21 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aminity', to='tenants.tenant')),
            ],
            options={
                'db_table': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('hire_date', models.DateField()),
                ('ROLE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actors.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('grade_level', models.CharField(max_length=10)),
                ('enrollment_date', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='actors.standard')),
                ('students', models.ManyToManyField(blank=True, related_name='batches', to='actors.student')),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='StudentAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.amenity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.student')),
            ],
            options={
                'db_table': 'student_amenities',
            },
        ),
        migrations.AddIndex(
            model_name='amenity',
            index=models.Index(fields=['name'], name='idx_amenity_name'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('tenant', 'email'), ('tenant', 'staff_id')},
        ),
        migrations.AlterUniqueTogether(
            name='standard',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('tenant', 'email'), ('tenant', 'student_id')},
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['academic_year'], name='idx_batch_academic_year'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_batch_dates'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('standard', 'code')},
        ),
        migrations.AddIndex(
            model_name='studentamenity',
            index=models.Index(fields=['student', 'start_date', 'end_date'], name='idx_student_amenity_dates'),
        ),
        migrations.AddIndex(
            model_name='studentamenity',
            index=models.Index(fields=['amenity'], name='idx_student_amenity_amenity'),
        ),
        migrations.AlterUniqueTogether(
            name='studentamenity',
            unique_together={('student', 'amenity', 'start_date')},
        ),
    ]
