# Generated by Django 5.2.1 on 2025-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enrollment_date',
            new_name='joined_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='whatsapp_phone',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mothor_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone_primary',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone_secondary',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
