# Generated by Django 5.2.1 on 2025-06-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_rename_enrollment_date_student_joined_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='ROLE',
            new_name='role',
        ),
    ]
