# Generated by Django 5.2.1 on 2025-06-27 03:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0003_rename_role_staff_role'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bonuses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('month_year', models.CharField(max_length=7)),
                ('pay_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='actors.staff')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_salaries', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-month_year', '-pay_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('TUITION', 'Tuition Fee'), ('ADMISSION', 'Admission Fee'), ('AMENITY', 'Amenity Fee'), ('OTHER', 'Other Fee')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateField()),
                ('month_year', models.CharField(blank=True, max_length=7)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='actors.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('TUITION_FEE', 'Tuition Fee'), ('ADMISSION_FEE', 'Admission Fee'), ('AMENITY_FEE', 'Amenity Fee'), ('OTHER_INCOME', 'Other Income'), ('STAFF_SALARY', 'Staff Salary'), ('OTHER_EXPENSE', 'Other Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.expensetype')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='actors.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='actors.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=15)),
                ('payment_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='tenants.tenant')),
                ('staff_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.staffsalary')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payment', to='finance.transaction')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=15)),
                ('payment_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='tenants.tenant')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.studentfee')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payment', to='finance.transaction')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='expensetype',
            index=models.Index(fields=['tenant', 'is_active'], name='finance_exp_tenant__8099ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensetype',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='staffsalary',
            index=models.Index(fields=['tenant', 'staff'], name='finance_sta_tenant__6a6c68_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsalary',
            index=models.Index(fields=['tenant', 'status'], name='finance_sta_tenant__585d94_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsalary',
            index=models.Index(fields=['tenant', 'month_year'], name='finance_sta_tenant__9e168f_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsalary',
            index=models.Index(fields=['pay_date'], name='finance_sta_pay_dat_963ccc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffsalary',
            unique_together={('tenant', 'staff', 'month_year')},
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['tenant', 'student'], name='finance_stu_tenant__0b87c2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['tenant', 'status'], name='finance_stu_tenant__6b762c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['tenant', 'due_date'], name='finance_stu_tenant__4ee323_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['month_year'], name='finance_stu_month_y_7e9bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'transaction_type'], name='finance_tra_tenant__e9d362_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'transaction_date'], name='finance_tra_tenant__62514e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'category'], name='finance_tra_tenant__0d0eca_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['student'], name='finance_tra_student_38322f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['staff'], name='finance_tra_staff_i_332a56_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['tenant', 'payment_date'], name='finance_sal_tenant__3dfc36_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['staff_salary'], name='finance_sal_staff_s_8fe093_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['tenant', 'payment_date'], name='finance_fee_tenant__911f11_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['student_fee'], name='finance_fee_student_6666f5_idx'),
        ),
    ]
