# Generated by Django 5.2.1 on 2025-06-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_references/fees/'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_references/salaries/'),
        ),
    ]
